export type ChecklistSeedItem = {
  order: number;
  stage: string;
  itemText: string;
  milestoneName: string | null;
};

// Originally transcribed verbatim from PM_Checklist_Tracker.xlsx (PM/DevOps
// sheets); regenerated by scripts/checklist-type-reassignment-map.mjs to
// reflect the 5-checklist reassignment applied to production in the
// "reassign_checklist_types" migration — kept in sync with that migration's
// mapping so a from-scratch environment (scripts/seed-checklist-template.ts
// against an empty DB) produces the same structure as the live, migrated
// database, rather than the old pre-split stage names.
export const PM_CHECKLIST_SEED: ChecklistSeedItem[] = [
  { order: 1, stage: "Governance", itemText: "Collect RFP, Proposal, and Contract/PO copies", milestoneName: null },
  { order: 2, stage: "Governance", itemText: "Send project initiation email to assigned PM", milestoneName: null },
  { order: 3, stage: "Governance", itemText: "Confirm client-approved platforms and performance expectations (Quest/Vision Pro/WebXR/AR/PCVR)", milestoneName: "Platforms Confirmed" },
  { order: 4, stage: "Governance", itemText: "Create MS Teams channel and SharePoint space for the project", milestoneName: null },
  { order: 5, stage: "Planning", itemText: "Complete and approve Definition of Ready (DoR)", milestoneName: "DoR Approved" },
  { order: 6, stage: "Planning", itemText: "Draft Project Management Plan (use PMP_Template.docx)", milestoneName: "PMP Approved" },
  { order: 7, stage: "Planning", itemText: "Define fixed-budget contingency/buffer percentage in the PM Plan", milestoneName: null },
  { order: 8, stage: "Planning", itemText: "Define CR pricing basis (man-day rate used for paid change requests)", milestoneName: null },
  { order: 9, stage: "Planning", itemText: "Define budget/schedule overrun escalation thresholds", milestoneName: null },
  { order: 10, stage: "Planning", itemText: "Development estimation of Epics in story points", milestoneName: null },
  { order: 11, stage: "Planning", itemText: "Build WBS Level 1", milestoneName: null },
  { order: 12, stage: "Baselines", itemText: "Map each milestone (~1 month cadence) to a payment tranche in the schedule", milestoneName: "Payment Schedule Approved" },
  { order: 13, stage: "Planning", itemText: "Set up WBS ID <-> SRS traceability (Product Backlog)", milestoneName: null },
  { order: 14, stage: "Gates", itemText: "Hold project kickoff meeting with client present", milestoneName: "Kickoff Complete" },
  { order: 15, stage: "Approvals", itemText: "Share SRS with estimation with client", milestoneName: null },
  { order: 16, stage: "Baselines", itemText: "Review and confirm payment terms and schedule", milestoneName: null },
  { order: 17, stage: "Planning", itemText: "Upload final pre-development documents to the project repository", milestoneName: null },
  { order: 18, stage: "Baselines", itemText: "Confirm Feature Definition Sheet and scope boundaries with client", milestoneName: null },
  { order: 19, stage: "Planning", itemText: "Hold backlog refinement / release planning meeting; add signed CRs to WBS", milestoneName: null },
  { order: 20, stage: "Planning", itemText: "Hold sprint planning meeting; send SRS Sprint PDF to client", milestoneName: null },
  { order: 21, stage: "Governance", itemText: "Log daily standups and time entries in PM tool", milestoneName: null },
  { order: 22, stage: "Governance", itemText: "Record and share sprint review demo with client and stakeholders", milestoneName: null },
  { order: 23, stage: "Governance", itemText: "Update CPI/SPI report weekly; escalate if beyond defined threshold", milestoneName: null },
  { order: 24, stage: "Governance", itemText: "Hold sprint retrospective (minimum monthly)", milestoneName: null },
  { order: 25, stage: "Governance", itemText: "Hold project status update meeting (minimum monthly, twice preferred)", milestoneName: null },
  { order: 26, stage: "Gates", itemText: "Submit and obtain platform/app-store certification", milestoneName: "Store Approved" },
  { order: 27, stage: "Approvals", itemText: "Obtain UAT sign-off from client", milestoneName: "UAT Signed Off" },
  { order: 28, stage: "Closure", itemText: "Send completion & release report to stakeholders; raise invoice per payment schedule", milestoneName: null },
  { order: 29, stage: "Closure", itemText: "Send Project Closure Report; obtain formal completion certificate", milestoneName: "Project Closed" },
  { order: 30, stage: "Closure", itemText: "Conduct customer satisfaction survey", milestoneName: null },
  { order: 31, stage: "Closure", itemText: "Deliver knowledge transfer package", milestoneName: null },
  { order: 32, stage: "Closure", itemText: "Activate support/AMC terms per contract", milestoneName: null },
  { order: 33, stage: "Closure", itemText: "Evaluate opportunity to transition from fixed-price to time & material model", milestoneName: null },
  { order: 34, stage: "Planning", itemText: "Conduct initial risk identification workshop; populate the Risk Register with top risks, severity, and mitigation owners", milestoneName: null },
];

// All 3 items consolidated onto "Development" — spreading only 3 items
// across 3 different stages (Code Review/Development/Performance) rendered
// as three near-empty 1-item stage cards. Architecture/Code Review/
// Performance/Technical QA stay in ENGINEERING_STAGES for future growth,
// just inert (0 rows) until real content justifies splitting back out.
export const ENGINEERING_CHECKLIST_SEED: ChecklistSeedItem[] = [
  { order: 1, stage: "Development", itemText: "Run automated AI code review (Git Action) on every PR; senior dev manual review before merge", milestoneName: null },
  { order: 2, stage: "Development", itemText: "Validate asset imports; test API integration on staging; implement error handling/fallback", milestoneName: null },
  { order: 3, stage: "Development", itemText: "Run final optimization pass", milestoneName: null },
];

// Device Testing folded into Functional Testing (device-level testing is a
// form of functional testing) — was a lone 1-item stage next to Test
// Planning/Functional Testing. Device Testing/Regression/UAT stay in
// QA_STAGES for future growth, just inert until populated.
export const QA_CHECKLIST_SEED: ChecklistSeedItem[] = [
  { order: 1, stage: "Test Planning", itemText: "Define Definition of Done (DoD) checklist, including XR-specific criteria", milestoneName: null },
  { order: 2, stage: "Functional Testing", itemText: "Run device-level testing each sprint (FPS, draw calls, shader complexity)", milestoneName: null },
  { order: 3, stage: "Functional Testing", itemText: "Run comfort & accessibility QA each sprint", milestoneName: null },
  { order: 4, stage: "Functional Testing", itemText: "Execute test cases; log and retest defects", milestoneName: null },
  { order: 5, stage: "Test Planning", itemText: "Define target performance budget per platform (FPS, draw calls, triangle/poly count, memory)", milestoneName: null },
];

export const DEVOPS_CHECKLIST_SEED: ChecklistSeedItem[] = [
  { order: 1, stage: "Infrastructure", itemText: "Create Git repository for code AND set up asset version control (Git LFS / DAM) for large 3D files", milestoneName: "Repos Ready" },
  { order: 2, stage: "CI/CD", itemText: "Deploy release candidate to UAT; run and pass smoke test", milestoneName: null },
  { order: 3, stage: "CI/CD", itemText: "Validate build pipeline", milestoneName: null },
  { order: 4, stage: "Security", itemText: "Run security vulnerability assessment (ZAP, MobSF)", milestoneName: null },
  { order: 5, stage: "CI/CD", itemText: "Schedule and execute production deployment; run smoke test in production", milestoneName: "Go-Live" },
  { order: 6, stage: "Infrastructure", itemText: "Provision cloud infrastructure as code (Terraform/Bicep/ARM)", milestoneName: null },
  { order: 7, stage: "Infrastructure", itemText: "Set up Dev / Staging / Production environments", milestoneName: null },
  { order: 8, stage: "Infrastructure", itemText: "Containerize services (Docker) and set up registry", milestoneName: null },
  { order: 9, stage: "Infrastructure", itemText: "Set up orchestration (Kubernetes / Container Apps / App Service)", milestoneName: null },
  { order: 10, stage: "CI/CD", itemText: "Define branching strategy & PR review process", milestoneName: null },
  { order: 11, stage: "CI/CD", itemText: "Build CI pipeline (build, lint, unit test on PR)", milestoneName: "CI Pipeline Green" },
  { order: 12, stage: "CI/CD", itemText: "Build CD pipeline (auto-deploy to Dev/Staging, gated Prod)", milestoneName: null },
  { order: 13, stage: "CI/CD", itemText: "Set up automated integration/regression test stage", milestoneName: null },
  { order: 14, stage: "Security", itemText: "Configure secrets management (Key Vault / Vault / SSM)", milestoneName: null },
  { order: 15, stage: "Security", itemText: "Run SAST/DAST and dependency vulnerability scanning", milestoneName: null },
  { order: 16, stage: "Security", itemText: "Set up access control / least-privilege IAM roles", milestoneName: null },
  { order: 17, stage: "Monitoring", itemText: "Set up monitoring, logging & alerting", milestoneName: null },
  { order: 18, stage: "Monitoring", itemText: "Configure autoscaling & load balancing", milestoneName: null },
  { order: 19, stage: "Monitoring", itemText: "Define backup & disaster recovery plan", milestoneName: null },
  { order: 20, stage: "Monitoring", itemText: "Run load/performance testing pre-launch", milestoneName: null },
  { order: 21, stage: "Monitoring", itemText: "Define release & rollback runbook", milestoneName: "Release Process Approved" },
  { order: 22, stage: "Monitoring", itemText: "Set up incident response process & on-call rotation", milestoneName: null },
  { order: 23, stage: "Monitoring", itemText: "Production go-live and post-deploy verification", milestoneName: "Production Go-Live" },
];

// 3D folded into Assets (3D graybox work is asset creation) — was a lone
// 1-item stage next to Assets' own lone 1-item. Now Storyboard/UX/Assets are
// evenly balanced at 2 items each. XR Validation and a standalone 3D stay in
// CREATIVE_XR_STAGES for future growth, just inert until populated.
export const CREATIVE_XR_CHECKLIST_SEED: ChecklistSeedItem[] = [
  { order: 1, stage: "UX", itemText: "Approve experience flow & interaction map", milestoneName: "Experience Flow Approved" },
  { order: 2, stage: "Assets", itemText: "Define 3D assets plan; plan and validate environment graybox", milestoneName: null },
  { order: 3, stage: "UX", itemText: "Prepare Figma / 3D UX mockups", milestoneName: null },
  { order: 4, stage: "Storyboard", itemText: "Run Creative Huddle workshop with client", milestoneName: null },
  { order: 5, stage: "Storyboard", itemText: "Finalize Experience Flow / storyboard", milestoneName: "Creative Direction Approved" },
  { order: 6, stage: "Assets", itemText: "Approve Visual Style Reference (mood board, sample assets)", milestoneName: null },
];

export const PM_STAGES = [
  // Only ever populated on a project won from a Presales opportunity — see
  // winPresalesProject in app/presales/actions.ts. Empty on every other
  // project; ChecklistTable and currentStage() both already skip stages
  // with 0 rows, so this is inert everywhere else.
  "Presales",
  "Governance",
  "Planning",
  "Approvals",
  "Baselines",
  "Gates",
  "Closure",
] as const;

// Reassigned from a wider 5-category list (Infrastructure/CI-CD/Security/
// Reliability/Release & Ops) — Reliability and Release & Ops content folds
// into Monitoring as part of the same migration that split PM_STAGES above.
export const DEVOPS_CATEGORIES = ["Infrastructure", "CI/CD", "Security", "Monitoring"] as const;

// New checklist types (see lib/checklist-types.ts) — no existing ChecklistItem
// rows use these yet, so unlike PM_STAGES/DEVOPS_CATEGORIES these are safe to
// define with their final content immediately; there's nothing to backfill.
export const ENGINEERING_STAGES = ["Architecture", "Development", "Code Review", "Performance", "Technical QA"] as const;

export const QA_STAGES = ["Test Planning", "Functional Testing", "Device Testing", "Regression", "UAT"] as const;

export const CREATIVE_XR_STAGES = ["Storyboard", "3D", "UX", "Assets", "XR Validation"] as const;

// Default rows from PMP_Template.docx, used to pre-populate a new project's PM Plan.
export const DEFAULT_STAKEHOLDER_ROWS = [
  { stakeholder: "Sponsor", role: "Approves budget/scope", responsibility: "Final decision authority", accessRequired: "Status reports" },
  { stakeholder: "Client / Product Owner", role: "Defines requirements", responsibility: "Prioritizes backlog, sign-off", accessRequired: "Project tools, environments as needed" },
  { stakeholder: "Project Manager", role: "Delivery ownership", responsibility: "Planning, coordination, risk mgmt", accessRequired: "All project systems" },
  { stakeholder: "Development Team", role: "Builds the solution", responsibility: "Implementation", accessRequired: "Repo, dev/staging environments" },
  { stakeholder: "QA Team", role: "Ensures quality", responsibility: "Testing, defect tracking", accessRequired: "Staging, test tools" },
  { stakeholder: "Operations / DevOps", role: "Deployment & infra", responsibility: "Release management", accessRequired: "Production environment, CI/CD" },
];

export const DEFAULT_COMMS_ROWS = [
  { audience: "Sponsor", frequency: "Bi-weekly", channel: "Email / report", content: "High-level status, risks, budget" },
  { audience: "Client", frequency: "Weekly", channel: "Call / email", content: "Progress, demos, blockers" },
  { audience: "Internal Team", frequency: "Daily", channel: "Standup", content: "Task status, impediments" },
  { audience: "All Stakeholders", frequency: "At milestones", channel: "Status report", content: "Milestone completion, next steps" },
];

export const DEFAULT_RACI_ROWS = [
  { activity: "Project Charter & Kickoff", pm: "A/R", tl: "C", ba: "C", leadEng: "I", creativeLead: "I" },
  { activity: "Requirements Gathering", pm: "C", tl: "C", ba: "A/R", leadEng: "I", creativeLead: "C" },
  { activity: "Scope Definition", pm: "A", tl: "C", ba: "R", leadEng: "C", creativeLead: "C" },
  { activity: "Creative Concept & Design Direction", pm: "I", tl: "I", ba: "C", leadEng: "I", creativeLead: "A/R" },
  { activity: "Technical Architecture", pm: "I", tl: "A/R", ba: "C", leadEng: "R", creativeLead: "I" },
  { activity: "UI/UX Design", pm: "I", tl: "I", ba: "C", leadEng: "I", creativeLead: "A/R" },
  { activity: "Sprint Planning", pm: "A/R", tl: "C", ba: "C", leadEng: "C", creativeLead: "C" },
  { activity: "Development", pm: "I", tl: "A", ba: "I", leadEng: "R", creativeLead: "I" },
  { activity: "Code Review", pm: "I", tl: "A/R", ba: "I", leadEng: "R", creativeLead: "I" },
  { activity: "QA / Testing", pm: "R", tl: "C", ba: "C", leadEng: "C", creativeLead: "I" },
  { activity: "UAT Coordination", pm: "A/R", tl: "I", ba: "C", leadEng: "I", creativeLead: "I" },
  { activity: "Deployment / Release", pm: "A", tl: "R", ba: "I", leadEng: "R", creativeLead: "I" },
  { activity: "Client Communication", pm: "A/R", tl: "C", ba: "C", leadEng: "I", creativeLead: "C" },
  { activity: "Risk Management", pm: "A/R", tl: "C", ba: "C", leadEng: "C", creativeLead: "I" },
  { activity: "Change Request Handling", pm: "A/R", tl: "C", ba: "R", leadEng: "C", creativeLead: "C" },
  { activity: "Documentation", pm: "A", tl: "C", ba: "R", leadEng: "C", creativeLead: "I" },
  { activity: "Retrospective / Project Closure", pm: "A/R", tl: "C", ba: "C", leadEng: "C", creativeLead: "C" },
];
